language: python
python: 3.6
install:
  - pip install jenkinsapi
  - pip install github3.py
script: 
  - cd scripts
  - git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH
  - python jen.py
  - bash comment.sh